services:
  weather-db:
    image: postgres:15
    restart: always
    container_name: weather-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  weather-api:
    build: .
    container_name: weather-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - weather-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    env_file:
      - .env

volumes:
  postgres_data:
